version: '2'
services:
  db:
    image: postgres:9.5
    ports:
      - "5432"
  app:
    build: .
    command: bash -c "mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
